### ISSUE TITLE
Missing stuff

### ISSUE THREAD

**Issue by Mecanik** [chancity/CSharp-AntiCaptcha#1]
Very nice library, however with the UI you cannot add any tasks...

Tried adding from code, but it does not work as expected.

**Comment by Mecanik** [comment]
So the UI is just for adding keys and viewing tasks ? That doesn't really make sense...

**Comment by chancity** [comment]
The UI was made for my specific use case.  You will have to expand the add key form with more settings.  You can also double click the key to view the current and old captcha request/responses

**Comment by chancity** [comment]
Actually decoupling the tasks from the key is probably the best way to go...

**Comment by Mecanik** [comment]
I really like the project, especially the UI, but I am more c++ and other languages oriented and creating functionality in your library to add tasks is very confusing -_-. Especially because I haven’t worked with C# in ages... :)

**Comment by Mecanik** [comment]
Actually, how did you use this without tasks ?

**Comment by chancity** [comment]
There are tasks https://github.com/chancity/CSharp-AntiCaptcha/tree/master/src/CreateTask

**Comment by chancity** [comment]
var solutionUsingKey = await key.GetSolvedCaptcha(new NoCaptchaTaskProxyless("https://someurl.com", "google public key"));

**Comment by Mecanik** [comment]
Yes, tried that. Right after I enter an API key, but it’s not listing the task or work ...
